{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Not Found: /favicon.ico", "status_code": 404, "request": "<WSGIRequest: GET '/favicon.ico'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 490, in get\n    Q(doc_name__icontains=query_sets)\nUnboundLocalError: local variable 'query_sets' referenced before assignment", "status_code": 500, "request": "<WSGIRequest: GET '/search/'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 490, in get\n    Q(content__icontains=query_sets)\nUnboundLocalError: local variable 'query_sets' referenced before assignment", "status_code": 500, "request": "<WSGIRequest: GET '/search/'>"}
{"message": "Internal Server Error: /search-docs/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 450, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1478, in build_filter\n    condition = self.build_lookup(lookups, col, value)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1308, in build_lookup\n    raise ValueError(\"Cannot use None as a query value\")\nValueError: Cannot use None as a query value", "status_code": 500, "request": "<WSGIRequest: GET '/search-docs/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search-docs/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 450, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1478, in build_filter\n    condition = self.build_lookup(lookups, col, value)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1308, in build_lookup\n    raise ValueError(\"Cannot use None as a query value\")\nValueError: Cannot use None as a query value", "status_code": 500, "request": "<WSGIRequest: GET '/search-docs/?z=%D0%A4%D0%B0'>"}
{"message": "Internal Server Error: /search-docs/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 450, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1478, in build_filter\n    condition = self.build_lookup(lookups, col, value)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1308, in build_lookup\n    raise ValueError(\"Cannot use None as a query value\")\nValueError: Cannot use None as a query value", "status_code": 500, "request": "<WSGIRequest: GET '/search-docs/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 469, in get\n    query_sets.append(Files.objects.search(query=q))\nAttributeError: 'Manager' object has no attribute 'search'", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 469, in get\n    query_sets.append(Files.objects.search(query=q))\nAttributeError: 'Manager' object has no attribute 'search'", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 467, in get_queryset\n    query_sets.append(Files.objects.filter(query=q))\nNameError: name 'q' is not defined", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 467, in get_queryset\n    query_sets.append(Files.objects.filter(query=q))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1407, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1217, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: add_data, file, file_name, file_version, id, relationsdocuments, relationsfiles, slug", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 474, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1407, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1217, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, doc_name, doc_type, document, document_language, id, relationsdocuments, tag_relation", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 474, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1407, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1217, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'file_name' into field. Choices are: description, doc_name, doc_type, document, document_language, id, relationsdocuments, tag_relation", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 473, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1407, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1217, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'file_name' into field. Choices are: description, doc_name, doc_type, document, document_language, id, relationsdocuments, tag_relation", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 473, in get_queryset\n    object_list = Documents.objects.filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1421, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1439, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 1446, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1532, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1388, in build_filter\n    return self._add_q(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1562, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1407, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1217, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1709, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'file_name' into field. Choices are: description, doc_name, doc_type, document, document_language, id, relationsdocuments, tag_relation", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 473, in get_queryset\n    object_list = final_set.objects.filter(\nAttributeError: 'list' object has no attribute 'objects'", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 473, in get_queryset\n    object_list = final_set.index(\nValueError: <Q: (OR: ('file_name__icontains', []), ('doc_name__icontains', []))> is not in list", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 473, in get_queryset\n    object_list = final_set.index(\nValueError: <Q: (OR: ('file_name__icontains', []), ('doc_name__icontains', []))> is not in list", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 463, in get_queryset\n    query_set_1 = Files.objects.get(file_name=q)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 650, in get\n    raise self.model.DoesNotExist(\nsystem.models.Files.DoesNotExist: Files matching query does not exist.", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 465, in get_queryset\n    final_set = query_set_1 + query_set_2\nTypeError: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 1026, in find_library\n    return parser.libraries[name]\nKeyError: 'bootstrap34'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 220, in _get_response\n    response = response.render()\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 114, in render\n    self.content = self.rendered_content\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 90, in rendered_content\n    template = self.resolve_template(self.template_name)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 72, in resolve_template\n    return select_template(template, using=self.using)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\loader.py\", line 42, in select_template\n    return engine.get_template(template_name)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\backends\\django.py\", line 33, in get_template\n    return Template(self.engine.get_template(template_name), self)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\engine.py\", line 175, in get_template\n    template, origin = self.find_template(template_name)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\engine.py\", line 157, in find_template\n    template = loader.get_template(name, skip=skip)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\loaders\\cached.py\", line 57, in get_template\n    template = super().get_template(template_name, skip)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\loaders\\base.py\", line 28, in get_template\n    return Template(\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 154, in __init__\n    self.nodelist = self.compile_nodelist()\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 200, in compile_nodelist\n    return parser.parse()\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 513, in parse\n    raise self.error(token, e)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 511, in parse\n    compiled_result = compile_func(self, token)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 1088, in load\n    lib = find_library(parser, name)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 1028, in find_library\n    raise TemplateSyntaxError(\ndjango.template.exceptions.TemplateSyntaxError: 'bootstrap34' is not a registered tag library. Must be one of:\nadmin_list\nadmin_modify\nadmin_urls\nbootstrap5\ncache\ncat_entities\ncat_file\ncrispy_forms_field\ncrispy_forms_filters\ncrispy_forms_tags\ncrispy_forms_utils\ndoc_file_relation\ndoc_files\ngroup_tag\ni18n\njavascript_value\nl10n\nlog\nmptt_admin\nmptt_tags\nstatic\ntz", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 220, in _get_response\n    response = response.render()\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 114, in render\n    self.content = self.rendered_content\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 92, in rendered_content\n    return template.render(context, self._request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\backends\\django.py\", line 61, in render\n    return self.template.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 175, in render\n    return self._render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 167, in _render\n    return self.nodelist.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\loader_tags.py\", line 54, in render\n    result = self.nodelist.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 321, in render\n    return nodelist.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 238, in render\n    nodelist.append(node.render_annotated(context))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1064, in render\n    output = self.filter_expression.resolve(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 715, in resolve\n    obj = self.var.resolve(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 847, in resolve\n    value = self._resolve_lookup(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 914, in _resolve_lookup\n    current = current()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\models.py\", line 71, in get_absolute_url\n    return reverse('cat-files', kwargs={'slug': self.slug})\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\urls\\base.py\", line 88, in reverse\n    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\urls\\resolvers.py\", line 828, in _reverse_with_prefix\n    raise NoReverseMatch(msg)\ndjango.urls.exceptions.NoReverseMatch: Reverse for 'cat-files' with keyword arguments '{'slug': 'file1'}' not found. 1 pattern(s) tried: ['files\\\\-cat/\\\\Z']", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 463, in get_queryset\n    matches = Files.objects.all() | Documents.objects.all()\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\query.py\", line 479, in __or__\n    combined.query.combine(other.query, sql.OR)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 616, in combine\n    raise TypeError(\"Cannot combine queries on two different base models.\")\nTypeError: Cannot combine queries on two different base models.", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 220, in _get_response\n    response = response.render()\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 114, in render\n    self.content = self.rendered_content\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\response.py\", line 92, in rendered_content\n    return template.render(context, self._request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\backends\\django.py\", line 61, in render\n    return self.template.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 175, in render\n    return self._render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 167, in _render\n    return self.nodelist.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\loader_tags.py\", line 54, in render\n    result = self.nodelist.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 321, in render\n    return nodelist.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1005, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\defaulttags.py\", line 238, in render\n    nodelist.append(node.render_annotated(context))\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 966, in render_annotated\n    return self.render(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 1064, in render\n    output = self.filter_expression.resolve(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 715, in resolve\n    obj = self.var.resolve(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 847, in resolve\n    value = self._resolve_lookup(context)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\template\\base.py\", line 914, in _resolve_lookup\n    current = current()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\models.py\", line 71, in get_absolute_url\n    return reverse('cat-files', kwargs={'slug': self.slug})\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\urls\\base.py\", line 88, in reverse\n    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\urls\\resolvers.py\", line 828, in _reverse_with_prefix\n    raise NoReverseMatch(msg)\ndjango.urls.exceptions.NoReverseMatch: Reverse for 'cat-files' with keyword arguments '{'slug': 'file1'}' not found. 1 pattern(s) tried: ['files\\\\-cat/\\\\Z']", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Internal Server Error: /search/", "exc_info": "Traceback (most recent call last):\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\exception.py\", line 56, in inner\n    response = get_response(request)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\base.py\", line 142, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"F:\\Managing_system\\lib\\site-packages\\django\\views\\generic\\list.py\", line 154, in get\n    self.object_list = self.get_queryset()\n  File \"C:\\Users\\boris\\Documents\\GitHub\\Manag_system\\manage\\system\\views.py\", line 468, in get_queryset\n    print(files_list = Files.objects.filter(\nTypeError: 'files_list' is an invalid keyword argument for print()", "status_code": 500, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "Method Not Allowed (GET): /search/", "status_code": 405, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "Method Not Allowed: /search/", "status_code": 405, "request": "<WSGIRequest: GET '/search/?z=%D0%A4%D0%B0%D0%B9%D0%BB'>"}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u0430 "}
{"message": "\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u0430 "}
{"message": "New document added"}
{"message": "New file added"}
{"message": "New category added"}
{"message": "User login "}
{"message": "File Update "}
{"message": "Not Found: /favicon.ico", "status_code": 404, "request": "<WSGIRequest: GET '/favicon.ico'>"}
